# akari developer tasks.
#
# The React production build is committed because go:embed must see it at compile
# time and release cross-compiles should need only Go. Development targets rebuild
# it from frontend/ before generating the remaining templ homepage.

.PHONY: frontend-deps frontend frontend-check frontend-test generate build test vet fmt clean

frontend-deps:
	cd frontend && bun install --frozen-lockfile

frontend: frontend-deps
	cd frontend && bun run build

frontend-check: frontend-deps
	cd frontend && bun run check

frontend-test: frontend-deps
	cd frontend && bun run test

generate:
	go generate ./...

# Compile every package after rebuilding both frontend layers.
build: frontend generate
	go build ./...

# Run the test suite (regenerating templ output first). The store/parse/web
# integration tests skip themselves unless AKARI_TEST_DATABASE_URL is set; see
# the README.
#
# No `-p` pin is needed: the storetest gate is a cross-process semaphore (file
# locks keyed to the target Postgres), so the suite's peak connections are bounded
# at maxLiveStores x poolMaxConns no matter how many package binaries run at once.
# See the budget note in internal/server/storetest/gate.go.
test: frontend-check frontend-test frontend generate
	go test -race ./...

# Vet every package (regenerating templ output first).
vet: generate
	go vet ./...

# Report any file that is not gofmt-clean (regenerating templ output first so
# the generated files are present to check).
fmt: generate
	gofmt -l .

# Remove the generated templ output. It is regenerated by `make generate`.
clean:
	rm -f internal/server/web/*_templ.go
