# akari developer tasks.
#
# The web package's templ templates compile to Go through `templ generate`, and
# the generated internal/server/web/*_templ.go files are gitignored: the .templ
# files are the sole source of truth, regenerated on every build. So a fresh
# clone will not compile until `templ generate` has run once. Every build/test
# target here depends on `generate` so a clone is one `make build` from a binary.
#
# templ is pinned as a Go tool in go.mod (the `tool` directive), so it needs no
# separate install: `go generate ./...` runs `go tool templ generate` at the
# version the module pins.

.PHONY: generate build test vet fmt clean

# Regenerate the templ output. Run after editing any internal/server/web/*.templ.
generate:
	go generate ./...

# Compile every package (regenerating templ output first).
build: generate
	go build ./...

# Run the test suite (regenerating templ output first). The store/parse/web
# integration tests skip themselves unless AKARI_TEST_DATABASE_URL is set; see
# the README.
test: generate
	go test -race ./...

# Vet every package (regenerating templ output first).
vet: generate
	go vet ./...

# Report any file that is not gofmt-clean (regenerating templ output first so
# the generated files are present to check).
fmt: generate
	gofmt -l .

# Remove the generated templ output. It is regenerated by `make generate`.
clean:
	rm -f internal/server/web/*_templ.go
