package web

import (
	"strings"
	"testing"
	"time"

	"github.com/jssblck/akari/internal/server/store"
)

// cleanFirstPrompt turns a session's raw opening user message into a one-line
// title, peeling off the wrappers Claude Code adds (slash-command tags, the
// local-command caveat, a leading system reminder) and the markdown an injected
// message can lead with. The cases mirror the shapes seen in real ingested data.
func TestCleanFirstPrompt(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"plain prompt is unchanged", "please set up CI for akari builds", "please set up CI for akari builds"},
		{"multiline collapses to one line", "fix the bug\n\nin the parser", "fix the bug in the parser"},
		{
			"slash command reads as name and args",
			"<command-message>impeccable</command-message> <command-name>/impeccable</command-name> <command-args>init look at datadog</command-args>",
			"/impeccable init look at datadog",
		},
		{
			"slash command with no args is just the name",
			"<command-name>/clear</command-name> <command-args></command-args>",
			"/clear",
		},
		{
			"local-command caveat is stripped, command survives",
			"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond.</local-command-caveat> <command-name>/review</command-name> <command-args>PR 42</command-args>",
			"/review PR 42",
		},
		{
			"caveat with trailing prose keeps the prose",
			"<local-command-caveat>Caveat: blah blah do not respond</local-command-caveat> actually do the thing",
			"actually do the thing",
		},
		{
			"system reminder is stripped",
			"<system-reminder>You are a helpful assistant. Be terse.</system-reminder> summarize the diff",
			"summarize the diff",
		},
		{"leading markdown heading is dropped", "## Context Usage of the session", "Context Usage of the session"},
		{"empty stays empty", "", ""},
		{"whitespace only stays empty", "   \n\t  ", ""},
	}
	for _, c := range cases {
		if got := cleanFirstPrompt(c.in); got != c.want {
			t.Errorf("%s: cleanFirstPrompt(%q) = %q, want %q", c.name, c.in, got, c.want)
		}
	}
}

// A long prompt is cut on a word boundary with an ellipsis, never mid-word, and
// stays within the cap.
func TestCleanFirstPromptTruncates(t *testing.T) {
	long := strings.Repeat("alpha beta gamma delta ", 20)
	got := cleanFirstPrompt(long)
	if !strings.HasSuffix(got, "…") {
		t.Fatalf("a long title should end with an ellipsis, got %q", got)
	}
	if r := []rune(got); len(r) > titleMax+1 {
		t.Errorf("title length %d exceeds cap %d: %q", len(r), titleMax, got)
	}
	if strings.Contains(got, "alph…") || strings.Contains(got, "gam…") {
		t.Errorf("title should break on a word boundary, got %q", got)
	}
}

// SessionTitle falls back to a quiet "<agent> session" when the row has no usable
// opening prompt, flagging the result as not derived so the view can mute it.
func TestSessionTitleFallback(t *testing.T) {
	derivedTitle, derived := SessionTitle(store.SessionRow{
		SessionSummary: store.SessionSummary{Agent: "claude"},
		FirstPrompt:    "land the rocket",
	})
	if !derived || derivedTitle != "land the rocket" {
		t.Errorf("a real prompt should yield a derived title, got %q derived=%v", derivedTitle, derived)
	}
	// A promptless run that still has turns falls back to the agent label.
	fallback, derived := SessionTitle(store.SessionRow{
		SessionSummary: store.SessionSummary{Agent: "codex", MessageCount: 4},
		FirstPrompt:    "",
	})
	if derived || fallback != "codex session" {
		t.Errorf("a promptless row should fall back to the agent label, got %q derived=%v", fallback, derived)
	}
	// A session with no messages at all is named for being empty.
	empty, derived := SessionTitle(store.SessionRow{
		SessionSummary: store.SessionSummary{Agent: "claude", MessageCount: 0},
		FirstPrompt:    "",
	})
	if derived || empty != "empty session" {
		t.Errorf("a zero-message row should read as empty, got %q derived=%v", empty, derived)
	}
}

// dayBucket labels a session's last activity relative to a fixed clock and shares
// a key across same-day rows so the feed groups them together.
func TestDayBucket(t *testing.T) {
	now := time.Date(2026, 6, 29, 12, 0, 0, 0, time.UTC)
	at := func(d time.Duration) *time.Time { tt := now.Add(d); return &tt }

	cases := []struct {
		name      string
		t         *time.Time
		wantLabel string
	}{
		{"today", at(-2 * time.Hour), "Today"},
		{"yesterday", at(-26 * time.Hour), "Yesterday"},
		{"within the week reads as a weekday", at(-3 * 24 * time.Hour), "Friday"},
		{"older this year reads as a date", at(-40 * 24 * time.Hour), "Wed May 20"},
		{"missing timestamp is undated", nil, "Undated"},
	}
	for _, c := range cases {
		if _, label := dayBucket(now, c.t); label != c.wantLabel {
			t.Errorf("%s: label = %q, want %q", c.name, label, c.wantLabel)
		}
	}

	// Two same-day rows share a grouping key.
	k1, _ := dayBucket(now, at(-1*time.Hour))
	k2, _ := dayBucket(now, at(-5*time.Hour))
	if k1 != k2 {
		t.Errorf("same-day rows should share a key, got %q and %q", k1, k2)
	}
}

// buildSessionFeed groups rows by day in the most-recent order, fades a repeated
// project, and scales each row's token bar against the feed's largest session.
func TestBuildSessionFeed(t *testing.T) {
	now := time.Date(2026, 6, 29, 12, 0, 0, 0, time.UTC)
	today1 := now.Add(-1 * time.Hour)
	today2 := now.Add(-3 * time.Hour)
	yesterday := now.Add(-26 * time.Hour)
	rows := []store.SessionRow{
		{SessionSummary: store.SessionSummary{ID: 1, Agent: "claude", TotalInput: 1000, UpdatedAt: &today1}, ProjectID: 1, ProjectKey: "akari", ProjectName: "akari", ProjectKind: "remote", FirstPrompt: "a"},
		{SessionSummary: store.SessionSummary{ID: 2, Agent: "claude", TotalInput: 500, UpdatedAt: &today2}, ProjectID: 1, ProjectKey: "akari", ProjectName: "akari", ProjectKind: "remote", FirstPrompt: "b"},
		{SessionSummary: store.SessionSummary{ID: 3, Agent: "claude", TotalInput: 0, UpdatedAt: &yesterday}, ProjectID: 2, ProjectKey: "site", ProjectName: "site", ProjectKind: "remote", FirstPrompt: "c"},
	}

	groups := buildSessionFeed(now, rows, true)
	if len(groups) != 2 {
		t.Fatalf("want 2 day groups, got %d", len(groups))
	}
	if groups[0].Label != "Today" || len(groups[0].Rows) != 2 {
		t.Errorf("first group should be Today with 2 rows, got %q with %d", groups[0].Label, len(groups[0].Rows))
	}
	// The second Today row repeats the first row's project, so it fades; the first
	// does not.
	if groups[0].Rows[0].FadeProject {
		t.Error("the first row in a group should never fade its project")
	}
	if !groups[0].Rows[1].FadeProject {
		t.Error("a row repeating the project above it should fade")
	}
	// The bar uses a square-root scale against the feed maximum (1000), so the
	// 500-token row sits at sqrt(0.5) ~= 70%, not a linear 50%.
	if pct := groups[0].Rows[1].TokenPct; pct != 70 {
		t.Errorf("token bar should use a sqrt scale, got %d, want 70", pct)
	}
	// A zero-token row shows no bar.
	if pct := groups[1].Rows[0].TokenPct; pct != 0 {
		t.Errorf("a zero-token row should have no bar, got %d", pct)
	}

	// Ungrouped (any non-recent sort) yields a single, unlabeled group in order.
	flat := buildSessionFeed(now, rows, false)
	if len(flat) != 1 || flat[0].Label != "" || len(flat[0].Rows) != 3 {
		t.Errorf("ungrouped feed should be one unlabeled group of all rows, got %d groups", len(flat))
	}
}

// FeedTime renders the clock time of day, with a placeholder for a missing stamp.
func TestFeedTime(t *testing.T) {
	tt := time.Date(2026, 6, 29, 14, 22, 0, 0, time.UTC)
	if got := FeedTime(&tt); got != "14:22" {
		t.Errorf("FeedTime = %q, want 14:22", got)
	}
	if got := FeedTime(nil); got != "--:--" {
		t.Errorf("FeedTime(nil) = %q, want --:--", got)
	}
}
