package web

import "testing"

func TestStripPromptPreamble(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"plain prompt untouched", "please resolve issue #97, fixing all charts", "please resolve issue #97, fixing all charts"},
		{"slash command surfaces the name", "<command-message>tag-release</command-message> <command-name>/tag-release</command-name>", "/tag-release"},
		{"slash command with args", "<command-name>/model</command-name> <command-args>claude-opus-4-8</command-args>", "/model claude-opus-4-8"},
		{
			"local-command caveat stripped",
			"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat> so i'm despairing a bit on the ability to draw",
			"so i'm despairing a bit on the ability to draw",
		},
		{
			"agents.md preamble jumps to the task",
			"# AGENTS.md instructions <INSTRUCTIONS> ## Operating principles - Do not preserve backwards compatibility </INSTRUCTIONS> Maintain the dots agent config backup",
			"Maintain the dots agent config backup",
		},
		{"empty stays empty", "", ""},
		{"whitespace-only returns original", "   ", "   "},
		{
			"unclosed wrapper falls back to original",
			"<local-command-caveat>no close tag here and real content never arrives",
			"<local-command-caveat>no close tag here and real content never arrives",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := StripPromptPreamble(c.in); got != c.want {
				t.Fatalf("StripPromptPreamble(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

func TestRowGradeClass(t *testing.T) {
	g := func(s string) *string { return &s }
	cases := []struct {
		grade *string
		want  string
	}{
		{nil, ""},
		{g("A"), "q-good"},
		{g("B"), "q-good"},
		{g("C"), "q-watch"},
		{g("D"), "q-poor"},
		{g("F"), "q-poor"},
	}
	for _, c := range cases {
		if got := RowGradeClass(c.grade); got != c.want {
			t.Fatalf("RowGradeClass(%v) = %q, want %q", c.grade, got, c.want)
		}
	}
}

func TestRowOutcomeNote(t *testing.T) {
	cases := map[string]string{
		"completed": "",
		"unknown":   "",
		"":          "",
		"abandoned": "abandoned",
		"errored":   "errored",
	}
	for in, want := range cases {
		if got := RowOutcomeNote(in); got != want {
			t.Fatalf("RowOutcomeNote(%q) = %q, want %q", in, got, want)
		}
	}
}
