// Package frontend exposes the production React build as an embedded filesystem.
// Keeping the build artifact behind this package lets the HTTP server serve the app
// without knowing how Bun names or lays out generated assets.
package frontend

import (
	"bytes"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io/fs"
	"net/http"
	"strings"
	"sync"
)

//go:embed dist
var files embed.FS

var (
	distOnce sync.Once
	distFS   fs.FS
	distErr  error
)

func productionFS() (fs.FS, error) {
	distOnce.Do(func() {
		distFS, distErr = fs.Sub(files, "dist")
	})
	return distFS, distErr
}

// Assets serves immutable files generated by the frontend build.
func Assets() http.Handler {
	dist, err := productionFS()
	if err != nil {
		return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "embedded frontend unavailable", http.StatusInternalServerError)
		})
	}
	return http.FileServer(http.FS(dist))
}

// Index returns the React entry document embedded in the binary, externalized
// for the path prefix the request resolved ("" for a root deployment).
//
// The build uses Vite's relative base, so chunk-to-chunk resolution inside the
// bundle rides import.meta.url and needs no rewriting; only this document's
// own references are document-relative and would break on nested SPA routes
// (/sessions/123). Index rewrites them to absolute prefixed paths and injects
// the prefix as window.__AKARI_BASE_PATH__, which the router basename and the
// API client read back. The prefix arrives validated (config.NormalizePathPrefix),
// so it is safe to interpolate into markup.
func Index(basePath string) ([]byte, error) {
	indexMu.Lock()
	cached, ok := indexCache[basePath]
	indexMu.Unlock()
	if ok {
		return cached, nil
	}
	document, err := buildIndex(basePath)
	if err != nil {
		return nil, err
	}
	indexMu.Lock()
	if len(indexCache) < indexCacheCap {
		indexCache[basePath] = document
	}
	indexMu.Unlock()
	return document, nil
}

// indexCache memoizes the externalized entry document per base path. A
// deployment normally sees one prefix, but the header mode admits several, so
// the cache is capped instead of trusting header cardinality; past the cap the
// document is rebuilt per request, which is still just two string passes.
var (
	indexMu    sync.Mutex
	indexCache = map[string][]byte{}
)

const indexCacheCap = 32

func buildIndex(basePath string) ([]byte, error) {
	dist, err := productionFS()
	if err != nil {
		return nil, err
	}
	index, err := fs.ReadFile(dist, "index.html")
	if err != nil {
		return nil, err
	}
	// externalize edits by plain string replacement, which matches zero times
	// without complaint if a toolchain upgrade reshapes the document. Refuse to
	// serve in that case: a loud 500 beats an entry document whose assets or
	// injected base silently stop being prefixed.
	if !bytes.Contains(index, []byte(`"./assets/`)) || !bytes.Contains(index, []byte("<head>")) {
		return nil, errors.New("dist/index.html does not match the externalize markers; update frontend.externalize alongside the build output")
	}
	return externalize(index, basePath), nil
}

// externalize rewrites the entry document's own references against the
// external base path and injects the base for the application to read.
func externalize(index []byte, basePath string) []byte {
	document := string(index)
	// Vite emits the entry script and stylesheet document-relative under the
	// relative base ("./assets/..."); route them to the /app-assets mount the
	// server actually serves the build from.
	document = strings.ReplaceAll(document, `"./assets/`, `"`+basePath+`/app-assets/assets/`)
	// References the build does not manage (the favicon) are authored absolute.
	document = strings.ReplaceAll(document, `"/static/`, `"`+basePath+`/static/`)
	// The base rides a JSON string literal so no prefix byte can terminate the
	// script early, and the tag sits at the head's start so it executes before
	// the (deferred) module entry reads it.
	base, _ := json.Marshal(basePath)
	document = strings.Replace(document, "<head>",
		fmt.Sprintf("<head><script>window.__AKARI_BASE_PATH__=%s;</script>", base), 1)
	return []byte(document)
}

// Metadata describes the crawler-visible identity of a public React route. The
// browser still owns the rendered page, but link previews need these values in the
// first HTML response because social crawlers do not reliably execute JavaScript.
type Metadata struct {
	Title       string
	Description string
	URL         string
	Image       string
}

// Document returns the embedded entry document with route-specific metadata,
// externalized for the given base path like Index.
func Document(meta Metadata, basePath string) ([]byte, error) {
	index, err := Index(basePath)
	if err != nil {
		return nil, err
	}
	escape := html.EscapeString
	title := escape(meta.Title)
	if title == "" {
		title = "akari"
	}
	document := strings.Replace(string(index), "<title>akari</title>", "<title>"+title+"</title>", 1)
	var tags strings.Builder
	tags.WriteString(`<meta property="og:title" content="` + title + `" />`)
	tags.WriteString(`<meta name="twitter:title" content="` + title + `" />`)
	if meta.Description != "" {
		description := escape(meta.Description)
		tags.WriteString(`<meta name="description" content="` + description + `" />`)
		tags.WriteString(`<meta property="og:description" content="` + description + `" />`)
		tags.WriteString(`<meta name="twitter:description" content="` + description + `" />`)
	}
	if meta.URL != "" {
		url := escape(meta.URL)
		tags.WriteString(`<link rel="canonical" href="` + url + `" />`)
		tags.WriteString(`<meta property="og:url" content="` + url + `" />`)
	}
	if meta.Image != "" {
		image := escape(meta.Image)
		tags.WriteString(`<meta property="og:image" content="` + image + `" />`)
		tags.WriteString(`<meta name="twitter:image" content="` + image + `" />`)
		tags.WriteString(`<meta name="twitter:card" content="summary_large_image" />`)
	} else {
		tags.WriteString(`<meta name="twitter:card" content="summary" />`)
	}
	document = strings.Replace(document, "</head>", tags.String()+"</head>", 1)
	return []byte(document), nil
}
