// Package frontend exposes the production React build as an embedded filesystem.
// Keeping the build artifact behind this package lets the HTTP server serve the app
// without knowing how Bun names or lays out generated assets.
package frontend

import (
	"embed"
	"html"
	"io/fs"
	"net/http"
	"strings"
	"sync"
)

//go:embed dist
var files embed.FS

var (
	distOnce sync.Once
	distFS   fs.FS
	distErr  error
)

func productionFS() (fs.FS, error) {
	distOnce.Do(func() {
		distFS, distErr = fs.Sub(files, "dist")
	})
	return distFS, distErr
}

// Assets serves immutable files generated by the frontend build.
func Assets() http.Handler {
	dist, err := productionFS()
	if err != nil {
		return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "embedded frontend unavailable", http.StatusInternalServerError)
		})
	}
	return http.FileServer(http.FS(dist))
}

// Index returns the React entry document embedded in the binary.
func Index() ([]byte, error) {
	dist, err := productionFS()
	if err != nil {
		return nil, err
	}
	return fs.ReadFile(dist, "index.html")
}

// Metadata describes the crawler-visible identity of a public React route. The
// browser still owns the rendered page, but link previews need these values in the
// first HTML response because social crawlers do not reliably execute JavaScript.
type Metadata struct {
	Title       string
	Description string
	URL         string
	Image       string
}

// Document returns the embedded entry document with route-specific metadata.
func Document(meta Metadata) ([]byte, error) {
	index, err := Index()
	if err != nil {
		return nil, err
	}
	escape := html.EscapeString
	title := escape(meta.Title)
	if title == "" {
		title = "akari"
	}
	document := strings.Replace(string(index), "<title>akari</title>", "<title>"+title+"</title>", 1)
	var tags strings.Builder
	tags.WriteString(`<meta property="og:title" content="` + title + `" />`)
	tags.WriteString(`<meta name="twitter:title" content="` + title + `" />`)
	if meta.Description != "" {
		description := escape(meta.Description)
		tags.WriteString(`<meta name="description" content="` + description + `" />`)
		tags.WriteString(`<meta property="og:description" content="` + description + `" />`)
		tags.WriteString(`<meta name="twitter:description" content="` + description + `" />`)
	}
	if meta.URL != "" {
		url := escape(meta.URL)
		tags.WriteString(`<link rel="canonical" href="` + url + `" />`)
		tags.WriteString(`<meta property="og:url" content="` + url + `" />`)
	}
	if meta.Image != "" {
		image := escape(meta.Image)
		tags.WriteString(`<meta property="og:image" content="` + image + `" />`)
		tags.WriteString(`<meta name="twitter:image" content="` + image + `" />`)
		tags.WriteString(`<meta name="twitter:card" content="summary_large_image" />`)
	} else {
		tags.WriteString(`<meta name="twitter:card" content="summary" />`)
	}
	document = strings.Replace(document, "</head>", tags.String()+"</head>", 1)
	return []byte(document), nil
}
