/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/app/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read account tokens, connections, invites, and rebuild state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account read model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/account/connections/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an OAuth client connection */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    client_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connection revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RevokedResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/account/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a registration invitation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invite revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RevokedResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/account/overview-publication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Publish or unpublish the current user's overview */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            responses: {
                /** @description Publication updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicationResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the current application viewer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Viewer state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Viewer"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/guide/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the user guide index */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Guide chapter and chapter index */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GuideResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/guide/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a user guide chapter */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Guide chapter and chapter index */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GuideResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read quality and workflow insights */
        get: {
            parameters: {
                query?: {
                    range?: "7d" | "30d" | "90d" | "year" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Insights read model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InsightsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve an OAuth consent request for the signed-in user */
        get: {
            parameters: {
                query: {
                    client_id: string;
                    redirect_uri: string;
                    state: string;
                    code_challenge: string;
                    resource?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Consent read model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OAuthConsentResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read fleet usage analytics */
        get: {
            parameters: {
                query?: {
                    range?: "7d" | "30d" | "90d" | "year" | "all";
                    user?: number[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview read model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OverviewResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects with lifetime rollups */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectsResponse"];
                    };
                };
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one project with windowed sessions and analytics */
        get: {
            parameters: {
                query?: {
                    range?: "7d" | "30d" | "90d" | "year" | "all";
                    agent?: string;
                    machine?: string;
                    user?: string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project read model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProjectResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/projects/{id}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Publish or unpublish a project overview */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            responses: {
                /** @description Publication updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicationResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/public/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a published project overview */
        get: {
            parameters: {
                query?: {
                    range?: "7d" | "30d" | "90d" | "year" | "all";
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published project overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicProjectResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/public/sessions/{public_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a published session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    public_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published session snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicSessionResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/public/sessions/{public_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an earlier published transcript window */
        get: {
            parameters: {
                query: {
                    before: number;
                };
                header?: never;
                path: {
                    public_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published transcript page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicSessionResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/public/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a published user overview */
        get: {
            parameters: {
                query?: {
                    range?: "7d" | "30d" | "90d" | "year" | "all";
                };
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Published overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicOverviewResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/reparse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a full projection rebuild */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rebuild queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReparseStatusResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and filter sessions */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    project?: number;
                    agent?: string;
                    machine?: string;
                    user?: string;
                    grade?: "A" | "B" | "C" | "D" | "F" | "unscored";
                    outcome?: "completed" | "abandoned" | "errored" | "unknown";
                    after?: number;
                    range?: "7d" | "30d" | "90d" | "year" | "all";
                    sort?: "updated" | "messages" | "tokens" | "cost";
                    dir?: "asc" | "desc";
                    empty?: "1";
                    subagents?: "1";
                    spanned?: "1";
                    limit?: number;
                    /** @description Observed sort value paired with after for stable keyset pagination. */
                    after_value?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session collection and facets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a session audit and transcript tail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeletedSessionResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sessions/{id}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Publish or unpublish an owned session */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Publication"];
                };
            };
            responses: {
                /** @description Publication updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionPublicationResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sessions/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an earlier transcript window */
        get: {
            parameters: {
                query: {
                    before: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transcript page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TranscriptResponse"];
                    };
                };
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a browser session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
            responses: {
                /** @description Signed in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete the current browser session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an account and create a browser session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
            responses: {
                /** @description Account created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisteredUserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/blob/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a content-addressed blob */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sha256: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Stored */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already present */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/blobs/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check which content-addressed blobs are missing */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Missing blob hashes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Announce or reconcile a session upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnnounceSession"];
                };
            };
            responses: {
                /** @description Upload state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/session/{id}/chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append raw session bytes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Chunk accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/session/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Declare a session terminal and grade it */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/session/{id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a session upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reset */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a registration invitation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateInvite"];
                };
            };
            responses: {
                /** @description Invite created; the plaintext secret is returned once */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedInviteResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reparse/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream projection rebuild progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server-sent rebuild events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reparse/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read projection rebuild progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rebuild status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReparseStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/{id}/blob/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a content-addressed tool body referenced by a visible session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    sha256: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blob bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API tokens */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token collection */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokensResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create an API token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateToken"];
                };
            };
            responses: {
                /** @description Token created; the plaintext secret is returned once */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke an API token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check database connectivity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Database unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/app/sessions/{id}/append": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a session's turns past a rendered ordinal */
        get: {
            parameters: {
                query: {
                    after: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session snapshot fragment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                503: components["responses"]["ProjectionRebuilding"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountInvite: {
            /** Format: date-time */
            CreatedAt: string;
            CreatedBy: string;
            ExpiresAt: string | null;
            /** Format: int64 */
            ID: number;
            Note: string;
            RedeemedAt: string | null;
            RedeemedBy: string | null;
        };
        AccountResponse: {
            connections: components["schemas"]["OAuthGrant"][] | null;
            invites: components["schemas"]["AccountInvite"][] | null;
            reparse: components["schemas"]["Status"];
            tokens: components["schemas"]["AccountToken"][] | null;
            user: components["schemas"]["Viewer"];
        };
        AccountToken: {
            /** Format: date-time */
            CreatedAt: string;
            /** Format: int64 */
            ID: number;
            LastUsedAt: string | null;
            Name: string;
            RevokedAt: string | null;
            Scope: string;
        };
        Analytics: {
            Agents: components["schemas"]["Breakdown"][] | null;
            Cache: components["schemas"]["CacheStats"];
            CostIncomplete: boolean;
            Models: components["schemas"]["Breakdown"][] | null;
            Series: components["schemas"]["DayPoint"][] | null;
            /** Format: int64 */
            Sessions: number;
            /** Format: int64 */
            TotalCacheRead: number;
            /** Format: int64 */
            TotalCacheWrite: number;
            TotalCost: number;
            /** Format: int64 */
            TotalIn: number;
            /** Format: int64 */
            TotalOut: number;
            /** Format: int64 */
            TotalReasoning: number;
            Users: components["schemas"]["Breakdown"][] | null;
        };
        AnnounceSession: {
            /** @enum {string} */
            agent: "claude" | "codex" | "pi";
            source_session_id: string;
            /**
             * @default remote
             * @enum {string}
             */
            kind: "remote" | "standalone" | "orphaned";
            project_remote?: string;
            local_root?: string;
            git_branch?: string;
            cwd?: string;
            machine?: string;
            /** @default false */
            terminal: boolean;
        };
        AttachmentView: {
            /** Format: int64 */
            ByteLen: number;
            Filename: string;
            MediaType: string;
            /** Format: int64 */
            MessageOrdinal: number;
            SHA256: string;
        };
        Breakdown: {
            /** Format: int64 */
            CacheRead: number;
            /** Format: int64 */
            CacheWrite: number;
            CostIncomplete: boolean;
            CostUSD: number;
            /** Format: int64 */
            Input: number;
            Label: string;
            /** Format: int64 */
            Output: number;
            /** Format: int64 */
            Reasoning: number;
            /** Format: int64 */
            Sessions: number;
        };
        CacheStats: {
            /** Format: int64 */
            CacheRead: number;
            /** Format: int64 */
            CacheWrite: number;
            /** Format: int64 */
            Input: number;
            /** Format: int64 */
            Output: number;
            SavingsIncomplete: boolean;
            SavingsUSD: number;
        };
        Chapter: {
            /** Format: int64 */
            Order: number;
            Slug: string;
            Summary: string;
            Title: string;
        };
        ChurnFile: {
            /** Format: int64 */
            Edits: number;
            Path: string;
            Project: string;
            /** Format: int64 */
            ProjectID: number;
            /** Format: int64 */
            Sessions: number;
        };
        ChurnNode: {
            /** Format: int64 */
            Edits: number;
            Folder: string;
            Path: string;
            Project: string;
            /** Format: int64 */
            Sessions: number;
        };
        ChurnTrend: {
            /** Format: int64 */
            Clipped: number;
            Files: number[] | null;
            /** Format: int64 */
            Projects: number;
            ReEdits: number[] | null;
            /** Format: int64 */
            TotalHotFiles: number;
            /** Format: int64 */
            TotalReEdits: number;
            Tree: components["schemas"]["ChurnNode"][] | null;
        };
        ConcurrencyStats: {
            AvgConcurrent: number;
            BusiestUser: string;
            /** Format: int64 */
            BusiestUserPeak: number;
            /** Format: int64 */
            FleetPeak: number;
            /** Format: date-time */
            FleetPeakAt: string;
            /** Format: int64 */
            Sessions: number;
        };
        ContextBucket: {
            /** Format: int64 */
            Count: number;
            /** Format: int64 */
            Hi: number;
            /** Format: int64 */
            Lo: number;
        };
        ContextHealthStats: {
            /** Format: int64 */
            PeakTokensMax: number;
            /** Format: int64 */
            PeakTokensP50: number;
            /** Format: int64 */
            PeakTokensP90: number;
            /** Format: int64 */
            Sessions: number;
            /** Format: int64 */
            SessionsWithReset: number;
            /** Format: int64 */
            TotalResets: number;
        };
        ContextMarker: {
            Kind: string;
            /** Format: int64 */
            Tokens: number;
        };
        CreateInvite: {
            note?: string;
            expires_hours?: number;
        };
        CreateToken: {
            name: string;
            /**
             * @default ingest
             * @enum {string}
             */
            scope: "ingest" | "read" | "full";
        };
        CreatedInviteResponse: {
            expires_at: string | null;
            /** Format: int64 */
            id: number;
            invite_token: string;
            note: string;
        };
        CreatedTokenResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            scope: string;
            token: string;
        };
        DateRange: {
            /** Format: int64 */
            Days: number;
            Key: string;
            Label: string;
        };
        DayPoint: {
            /** Format: int64 */
            CacheRead: number;
            /** Format: int64 */
            CacheWrite: number;
            CostUSD: number;
            /** Format: date-time */
            Day: string;
            /** Format: int64 */
            Input: number;
            /** Format: int64 */
            Output: number;
        };
        DeletedSessionResponse: {
            deleted: boolean;
            /** Format: int64 */
            project_id: number;
        };
        Economics: {
            AbandonedIncomplete: boolean;
            AbandonedSharePct: number;
            CacheHitRate: number[] | null;
            CacheHitRateLatest: number;
            CacheMeasured: boolean[] | null;
            CacheSavings: number[] | null;
            CacheSavingsIncomplete: boolean;
            CostAbandoned: number[] | null;
            CostCompleted: number[] | null;
            CostIncomplete: boolean;
            CostOther: number[] | null;
            TotalAbandoned: number;
            TotalCacheSavings: number;
            TotalSpend: number;
        };
        Error: {
            error: string;
            code?: string;
        };
        FacetCount: {
            /** Format: int64 */
            Count: number;
            Value: string;
        };
        FacetValues: {
            Agents: string[] | null;
            Machines: string[] | null;
            Users: string[] | null;
        };
        FileChurn: {
            /** Format: int64 */
            Clipped: number;
            Files: components["schemas"]["ChurnFile"][] | null;
        };
        FleetMix: {
            Models: components["schemas"]["ModelSeries"][] | null;
            /** Format: int64 */
            NewestFirst: number;
            NewestModel: string;
        };
        Gallery: {
            CostIncomplete: boolean;
            LongestCostUSD: number;
            LongestDurationS: number;
            MedianCompletedCostUSD: number;
            MedianCostUSD: number;
            MedianDurationS: number;
            PriciestCostUSD: number;
            PriciestDurationS: number;
            Rows: components["schemas"]["GallerySession"][] | null;
            /** Format: int64 */
            Total: number;
        };
        GallerySession: {
            Archetype: string;
            CostIncomplete: boolean;
            CostUSD: number;
            DurationS: number;
            Grade: string;
            Outcome: string;
        };
        GlobalFacetValues: {
            Agents: components["schemas"]["FacetCount"][] | null;
            Machines: components["schemas"]["FacetCount"][] | null;
            Projects: components["schemas"]["ProjectFacet"][] | null;
            Users: components["schemas"]["FacetCount"][] | null;
        };
        GuideResponse: {
            chapters: components["schemas"]["Chapter"][] | null;
            github_url: string;
            headings: components["schemas"]["Heading"][] | null;
            raw_markdown: string;
            raw_path: string;
            slug: string;
            summary: string;
            title: string;
        };
        Heading: {
            ID: string;
            /** Format: int64 */
            Level: number;
            Text: string;
        };
        Insights: {
            Archetypes: components["schemas"]["LabeledCount"][] | null;
            Churn: components["schemas"]["FileChurn"];
            Concurrency: components["schemas"]["ConcurrencyStats"];
            Context: components["schemas"]["ContextHealthStats"];
            Hygiene: components["schemas"]["PromptHygiene"];
            Quality: components["schemas"]["QualityDistribution"];
            Tools: components["schemas"]["ToolStats"];
            Trends: components["schemas"]["Trends"] | null;
            Velocity: components["schemas"]["VelocityStats"];
        };
        InsightsResponse: {
            /** Format: date-time */
            generated_at: string;
            insights: components["schemas"]["Insights"];
            range: string;
            ranges: components["schemas"]["DateRange"][] | null;
        };
        LabeledCount: {
            /** Format: int64 */
            Count: number;
            Key: string;
        };
        Login: {
            username: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            is_admin: boolean;
            username: string;
        };
        Message: {
            Content: string;
            DuplicatePrompt: boolean;
            HasThinking: boolean;
            HasToolUse: boolean;
            Model: string;
            /** Format: int64 */
            Ordinal: number;
            /** Format: int64 */
            PromptDigest: number;
            PromptFactsCurrent: boolean;
            PromptNoCode: boolean;
            PromptShort: boolean;
            Role: string;
            /** Format: int64 */
            ThinkingBytes: number;
            ThinkingText: string;
            Timestamp: string | null;
            Usage: components["schemas"]["TurnUsage"] | null;
        };
        ModelFallback: {
            DeclinedCacheRead: number | null;
            DeclinedCacheWrite: number | null;
            DeclinedInput: number | null;
            DeclinedOutput: number | null;
            DedupKey: string;
            FromModel: string;
            MessageOrdinal: number | null;
            OccurredAt: string | null;
            RefusalCategory: string;
            RefusalExplanation: string;
            ToModel: string;
            Trigger: string;
        };
        ModelSeries: {
            /** Format: int64 */
            First: number;
            Model: string;
            Share: number[] | null;
            WindowShare: number;
        };
        OAuthConsentResponse: {
            app_csrf: string;
            client_id: string;
            client_name: string;
            code_challenge: string;
            csrf: string;
            redirect_uri: string;
            resource: string;
            state: string;
            username: string;
        };
        OAuthGrant: {
            ClientID: string;
            ClientName: string;
            /** Format: date-time */
            ConnectedAt: string;
            /** Format: date-time */
            LastUsedAt: string;
            Scope: string;
        };
        OverviewResponse: {
            analytics: components["schemas"]["Analytics"];
            range: string;
            ranges: components["schemas"]["DateRange"][] | null;
            selected_user_ids: number[] | null;
            users: components["schemas"]["OverviewUser"][] | null;
        };
        OverviewUser: {
            /** Format: int64 */
            ID: number;
            IsAdmin: boolean;
            Username: string;
        };
        ProjectFacet: {
            /** Format: int64 */
            Count: number;
            /** Format: int64 */
            ID: number;
            Key: string;
            Kind: string;
            Name: string;
        };
        ProjectResponse: {
            analytics: components["schemas"]["Analytics"];
            facets: components["schemas"]["FacetValues"];
            filter: components["schemas"]["SessionFilter"];
            insights: components["schemas"]["Insights"];
            project: components["schemas"]["ProjectSummary"];
            range: string;
            ranges: components["schemas"]["DateRange"][] | null;
            remainder: components["schemas"]["SessionRemainder"];
            sessions: components["schemas"]["SessionSummary"][] | null;
        };
        ProjectSummary: {
            CostIncomplete: boolean;
            DisplayName: string;
            Host: string;
            /** Format: int64 */
            ID: number;
            Kind: string;
            LastActivity: string | null;
            OverviewPublic: boolean;
            Owner: string;
            RemoteKey: string;
            Repo: string;
            /** Format: int64 */
            SessionCount: number;
            /** Format: int64 */
            TotalCacheRead: number;
            /** Format: int64 */
            TotalCacheWrite: number;
            TotalCostUSD: number;
            /** Format: int64 */
            TotalInput: number;
            /** Format: int64 */
            TotalOutput: number;
        };
        ProjectsResponse: {
            projects: components["schemas"]["ProjectSummary"][] | null;
            sparklines: {
                [key: string]: number[] | null;
            } | null;
        };
        PromptHygiene: {
            /** Format: int64 */
            Duplicate: number;
            /** Format: int64 */
            NoCodeContext: number;
            /** Format: int64 */
            Prompts: number;
            /** Format: int64 */
            Sessions: number;
            /** Format: int64 */
            Short: number;
            /** Format: int64 */
            UnstructuredStarts: number;
        };
        PublicOverviewResponse: {
            analytics: components["schemas"]["Analytics"];
            range: string;
            ranges: components["schemas"]["DateRange"][] | null;
            username: string;
        };
        PublicProjectResponse: {
            analytics: components["schemas"]["Analytics"];
            insights: components["schemas"]["Insights"];
            project: components["schemas"]["ProjectSummary"];
            range: string;
            ranges: components["schemas"]["DateRange"][] | null;
        };
        PublicSessionResponse: {
            snapshot: components["schemas"]["PublicSessionSnapshot"];
        };
        PublicSessionSnapshot: {
            Audit: components["schemas"]["SessionAudit"];
            Outline: components["schemas"]["Message"][] | null;
            Page: components["schemas"]["TranscriptPage"];
            /** Format: int64 */
            ProjectionRevision: number;
            Tools: components["schemas"]["ToolCallView"][] | null;
        };
        Publication: {
            published: boolean;
        };
        PublicationResponse: {
            published: boolean;
        };
        QualityDistribution: {
            /** Format: int64 */
            Graded: number;
            Grades: components["schemas"]["LabeledCount"][] | null;
            Outcomes: components["schemas"]["LabeledCount"][] | null;
            /** Format: int64 */
            Sessions: number;
        };
        Register: {
            username: string;
            /** Format: password */
            password: string;
            invite_token?: string;
        };
        RegisteredUserResponse: {
            /** Format: int64 */
            id: number;
            is_admin: boolean;
            username: string;
        };
        ReparseStatusResponse: {
            /** Format: int64 */
            done: number;
            /** Format: int64 */
            failed: number;
            in_progress: boolean;
            /** Format: date-time */
            started_at?: string;
            /** Format: int64 */
            total: number;
        };
        RevokedResponse: {
            revoked: boolean;
        };
        RhythmGrid: {
            Cells: (number[] | null)[] | null;
        };
        SearchSnippet: {
            /** Format: int64 */
            MatchEnd: number;
            /** Format: int64 */
            MatchStart: number;
            Text: string;
        };
        SessionAudit: {
            Detail: components["schemas"]["SessionDetail"];
            Fallbacks: components["schemas"]["ModelFallback"][] | null;
            Signals: components["schemas"]["SessionSignals"];
            Subagents: components["schemas"]["SubagentRow"][] | null;
        };
        SessionDetail: {
            Agent: string;
            CacheSavingsIncomplete: boolean;
            CostIncomplete: boolean;
            Cwd: string;
            EndedAt: string | null;
            GitBranch: string;
            /** Format: int64 */
            ID: number;
            LastActiveAt: string | null;
            Machine: string;
            /** Format: int64 */
            MessageCount: number;
            /** Format: int64 */
            ModelFallbackCount: number;
            /** Format: int64 */
            OwnerID: number;
            ParentID: number | null;
            /** Format: int64 */
            ProjectID: number;
            ProjectKey: string;
            ProjectKind: string;
            ProjectName: string;
            PublicID: string | null;
            StartedAt: string | null;
            Title: string;
            /** Format: int64 */
            TotalCacheRead: number;
            TotalCacheSavingsUSD: number;
            /** Format: int64 */
            TotalCacheWrite: number;
            TotalCostUSD: number;
            /** Format: int64 */
            TotalInput: number;
            /** Format: int64 */
            TotalOutput: number;
            /** Format: int64 */
            UserMessageCount: number;
            Username: string;
            Visibility: string;
        };
        SessionFilter: {
            /** Format: int64 */
            After: number;
            AfterVal: string;
            Agent: string;
            Desc: boolean;
            Grade: string;
            IncludeEmpty: boolean;
            IncludeSubagents: boolean;
            /** Format: int64 */
            Limit: number;
            Machine: string;
            /** Format: int64 */
            Offset: number;
            Outcome: string;
            /** Format: int64 */
            ProjectID: number;
            Query: string;
            Range: string;
            RequireSpan: boolean;
            /** Format: date-time */
            Since: string;
            Sort: string;
            Username: string;
        };
        SessionPublicationResponse: {
            public_id?: string;
            published: boolean;
        };
        SessionRemainder: {
            /** Format: int64 */
            CacheRead: number;
            /** Format: int64 */
            CacheWrite: number;
            CostIncomplete: boolean;
            CostUSD: number;
            /** Format: int64 */
            Input: number;
            /** Format: int64 */
            Output: number;
            /** Format: int64 */
            Sessions: number;
        };
        SessionResponse: {
            can_delete: boolean;
            owner: boolean;
            snapshot: components["schemas"]["SessionSnapshot"];
        };
        SessionRow: {
            Agent: string;
            CostIncomplete: boolean;
            EndedAt: string | null;
            GitBranch: string;
            Grade: string | null;
            /** Format: int64 */
            ID: number;
            LastActiveAt: string | null;
            Machine: string;
            /** Format: int64 */
            MessageCount: number;
            /** Format: int64 */
            ModelFallbackCount: number;
            Outcome: string;
            /** Format: int64 */
            ProjectID: number;
            ProjectKey: string;
            ProjectKind: string;
            ProjectName: string;
            PublicID: string | null;
            Search: components["schemas"]["SearchSnippet"];
            StartedAt: string | null;
            Title: string;
            /** Format: int64 */
            TotalCacheRead: number;
            /** Format: int64 */
            TotalCacheWrite: number;
            TotalCostUSD: number;
            /** Format: int64 */
            TotalInput: number;
            /** Format: int64 */
            TotalOutput: number;
            Tree: components["schemas"]["TreeRollup"];
            /** Format: int64 */
            UserMessageCount: number;
            Username: string;
            Visibility: string;
        };
        SessionSignals: {
            AssistantTurns: number | null;
            ContextResetCount: number | null;
            /** Format: int64 */
            DuplicatePromptCount: number;
            /** Format: int64 */
            EditChurn: number;
            Grade: string | null;
            /** Format: int64 */
            LongestFailureStreak: number;
            /** Format: int64 */
            NoCodeContextCount: number;
            Outcome: string;
            OutcomeConfidence: string;
            PeakContextTokens: number | null;
            /** Format: int64 */
            PromptCount: number;
            Score: number | null;
            /** Format: int64 */
            SessionID: number;
            /** Format: int64 */
            ShortPromptCount: number;
            ThinkingPeakTokens: number | null;
            ThinkingTailTokens: number | null;
            ThinkingTurns: number | null;
            /** Format: int64 */
            ToolCalls: number;
            /** Format: int64 */
            ToolFailures: number;
            /** Format: int64 */
            ToolRetries: number;
            UnstructuredStart: boolean;
        };
        SessionSnapshot: {
            Audit: components["schemas"]["SessionAudit"];
            /** Format: int64 */
            DupIDs: number;
            Outline: components["schemas"]["Message"][] | null;
            Page: components["schemas"]["TranscriptPage"];
            Tools: components["schemas"]["ToolCallView"][] | null;
        };
        SessionSummary: {
            Agent: string;
            CostIncomplete: boolean;
            EndedAt: string | null;
            GitBranch: string;
            /** Format: int64 */
            ID: number;
            LastActiveAt: string | null;
            Machine: string;
            /** Format: int64 */
            MessageCount: number;
            /** Format: int64 */
            ModelFallbackCount: number;
            PublicID: string | null;
            StartedAt: string | null;
            Title: string;
            /** Format: int64 */
            TotalCacheRead: number;
            /** Format: int64 */
            TotalCacheWrite: number;
            TotalCostUSD: number;
            /** Format: int64 */
            TotalInput: number;
            /** Format: int64 */
            TotalOutput: number;
            /** Format: int64 */
            UserMessageCount: number;
            Username: string;
            Visibility: string;
        };
        SessionsResponse: {
            facets: components["schemas"]["GlobalFacetValues"];
            filter: components["schemas"]["SessionFilter"];
            has_more: boolean;
            sessions: components["schemas"]["SessionRow"][] | null;
        };
        SignalTrends: {
            AbandonedCount: number[] | null;
            AbandonedRate: number[] | null;
            ArchetypeShare: ({
                [key: string]: number;
            } | null)[] | null;
            CompletedCount: number[] | null;
            CompletedRate: number[] | null;
            ContextHistogram: components["schemas"]["ContextBucket"][] | null;
            ContextMarkers: components["schemas"]["ContextMarker"][] | null;
            ContextResets: number[] | null;
            GPA: number[] | null;
            GradeShare: ({
                [key: string]: number;
            } | null)[] | null;
            HygieneNoCode: number[] | null;
            HygieneRepeated: number[] | null;
            HygieneTerse: number[] | null;
            HygieneUnstructured: number[] | null;
            OutcomeTotal: number[] | null;
        };
        Status: {
            /** Format: int64 */
            done: number;
            /** Format: int64 */
            failed: number;
            in_progress: boolean;
            /** Format: date-time */
            started_at?: string;
            /** Format: int64 */
            total: number;
        };
        StatusResponse: {
            status: string;
        };
        SubagentRow: {
            Agent: string;
            CostIncomplete: boolean;
            EndedAt: string | null;
            GitBranch: string;
            Grade: string | null;
            /** Format: int64 */
            ID: number;
            LastActiveAt: string | null;
            Machine: string;
            /** Format: int64 */
            MessageCount: number;
            /** Format: int64 */
            ModelFallbackCount: number;
            Outcome: string;
            PublicID: string | null;
            StartedAt: string | null;
            Title: string;
            /** Format: int64 */
            TotalCacheRead: number;
            /** Format: int64 */
            TotalCacheWrite: number;
            TotalCostUSD: number;
            /** Format: int64 */
            TotalInput: number;
            /** Format: int64 */
            TotalOutput: number;
            /** Format: int64 */
            UserMessageCount: number;
            Username: string;
            Visibility: string;
        };
        SubagentStats: {
            CostShare: number[] | null;
            CostShareIncomplete: boolean;
            CostThroughSubagentsPct: number;
            /** Format: int64 */
            DeepestTree: number;
            DelegateShare: number[] | null;
            FanoutOrder: string[] | null;
            FanoutRows: ({
                [key: string]: number;
            } | null)[] | null;
            SessionsThatDelegatePct: number;
            /** Format: int64 */
            SubagentSessionsInWindow: number;
        };
        TokenListItem: {
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            last_used_at: string | null;
            name: string;
            revoked_at: string | null;
            scope: string;
        };
        TokensResponse: {
            tokens: components["schemas"]["TokenListItem"][] | null;
        };
        ToolCallView: {
            /** Format: int64 */
            CallIndex: number;
            Category: string;
            Detail: string;
            FilePath: string;
            FileRelPath: string;
            /** Format: int64 */
            InputBytes: number;
            InputMediaType: string;
            InputSHA: string;
            /** Format: int64 */
            MessageOrdinal: number;
            /** Format: int64 */
            ResultBytes: number;
            ResultMediaType: string;
            ResultSHA: string;
            ResultStatus: string;
            ToolName: string;
        };
        ToolFailSeries: {
            Name: string;
            Rate: number[] | null;
        };
        ToolPoint: {
            /** Format: int64 */
            Calls: number;
            Category: string;
            /** Format: int64 */
            Failures: number;
            Name: string;
            /** Format: int64 */
            Sessions: number;
        };
        ToolStat: {
            /** Format: int64 */
            Calls: number;
            /** Format: int64 */
            Failures: number;
            Name: string;
        };
        ToolStats: {
            /** Format: int64 */
            Clipped: number;
            Tools: components["schemas"]["ToolStat"][] | null;
            /** Format: int64 */
            TotalCalls: number;
            /** Format: int64 */
            TotalFailures: number;
            /** Format: int64 */
            Turns: number;
        };
        ToolTrends: {
            FailFleet: number[] | null;
            FailWorst: components["schemas"]["ToolFailSeries"][] | null;
            Mix: ({
                [key: string]: number;
            } | null)[] | null;
            MixOrder: string[] | null;
            Reliability: components["schemas"]["ToolPoint"][] | null;
        };
        TranscriptPage: {
            Attachments: components["schemas"]["AttachmentView"][] | null;
            /** Format: int64 */
            EarlierCount: number;
            Fallbacks: components["schemas"]["ModelFallback"][] | null;
            HasEarlier: boolean;
            More: boolean;
            Msgs: components["schemas"]["Message"][] | null;
            Seed: components["schemas"]["Message"][] | null;
            Tools: components["schemas"]["ToolCallView"][] | null;
        };
        TranscriptResponse: {
            page: components["schemas"]["TranscriptPage"];
        };
        TreeRollup: {
            CostIncomplete: boolean;
            CostUSD: number;
            /** Format: int64 */
            SubagentCount: number;
        };
        Trends: {
            BucketStarts: string[] | null;
            Churn: components["schemas"]["ChurnTrend"];
            Economics: components["schemas"]["Economics"];
            FleetMix: components["schemas"]["FleetMix"];
            Gallery: components["schemas"]["Gallery"];
            Labels: string[] | null;
            Rhythm: components["schemas"]["RhythmGrid"];
            Signals: components["schemas"]["SignalTrends"];
            Subagents: components["schemas"]["SubagentStats"];
            Tools: components["schemas"]["ToolTrends"];
            Unit: string;
            Velocity: components["schemas"]["VelocityTrends"];
        };
        TurnUsage: {
            /** Format: int64 */
            CacheRead: number;
            /** Format: int64 */
            CacheWrite: number;
            /** Format: int64 */
            ContextTokens: number;
            CostIncomplete: boolean;
            CostUSD: number | null;
            /** Format: int64 */
            Input: number;
            /** Format: int64 */
            Output: number;
            /** Format: int64 */
            Reasoning: number;
        };
        VelocityStats: {
            ActiveSeconds: number;
            /** Format: int64 */
            FirstResponseP50: number;
            MsgsPerActiveMin: number;
            /** Format: int64 */
            ResponseP50: number;
            /** Format: int64 */
            ResponseP90: number;
            /** Format: int64 */
            Sessions: number;
            ToolsPerActiveMin: number;
            /** Format: int64 */
            Turns: number;
        };
        VelocityTrends: {
            ActiveHours: number[] | null;
            MsgsPerMin: number[] | null;
            ResponseP50: number[] | null;
            ResponseP90: number[] | null;
            ResponseP99: number[] | null;
            ToolsPerMin: number[] | null;
            WallHours: number[] | null;
        };
        Viewer: {
            authenticated: boolean;
            /** Format: int64 */
            user_id?: number;
            username?: string;
            is_admin: boolean;
            overview_public: boolean;
            csrf_token?: string;
            version: string;
        };
        ProjectionRebuild: {
            /** @constant */
            error: "projection rebuild in progress";
            /** @constant */
            code: "projection_rebuild";
            reparse: components["schemas"]["ReparseStatusResponse"];
        };
    };
    responses: {
        /** @description The request is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The credential does not have the required scope. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource does not exist or is not visible. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The parsed projection is rebuilding; retry after the requested delay. */
        ProjectionRebuilding: {
            headers: {
                /** @description Seconds before retrying. */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ProjectionRebuild"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
